# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Test
  jobs:
    - job:  asa
      steps:
        -  script:  each hello world0

- stage: DeployUS1
  dependsOn: Test    # this stage runs after Test
  jobs:
    - job:  asa
      steps:
        -  script:  each hello world1

- stage: DeployUS2
  dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test
  jobs:
    - job:  asa
      steps:
        -  script:  each hello world2

- stage: DeployEurope
  dependsOn:         # this stage runs after DeployUS1 and DeployUS2
  - DeployUS1
  - DeployUS2
  jobs:
    - job:  asa
      steps:
        -  script:  each hello world3
